### PR TITLE
Mahsa/eng 519 backend refactor note crud operation

### PR DESCRIPTION
**Pull request by mahsa-abadian**
# Description

refactor crud operation like using create and save method to add note to database
add interface for methods defined in `note.service.ts`
refactor the way we assign note to contact
refactor the way we filter note by using foreign key
small changes in note and contact entity
refactor the way we assign contact to organization

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
it was tested using rest client 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by AienTech — CHANGES_REQUESTED** [review]
please eaither use `yarn` or `npm`. for the matter, only `package-lock.json` or `yarn.lock` should exist in the project

**Review by mjavadHasanzade — APPROVED** [review]

**Review by hrahimi270 — APPROVED** [review]
I've tested and it's working fine.

**Comment by hrahimi270** [comment]
@mahsa-abadian  Error handling should be done for CRUD operations to check if the contact exists. If it doesn't exist, you should return an exception to the client. This should be done for all service functions on this branch.

**Review by hrahimi270 — APPROVED** [review]
We had some changes for better error handling.

**Review by armamini — APPROVED** [review]

**Pull request merged**
