### PR TITLE
Maryam/544 contact UI page

### PR DESCRIPTION
**Pull request by MaryPG21**
# Description

insert and design contact cards to show users their own contact.

Fixes #544
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

it is imported on the dashboard page to check location, color, and inputs.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ferizana92 — CHANGES_REQUESTED** [review]
please change main to dev.

**Comment by MaryPG21** [comment]
> please change main to dev.

I Do.

**Review by ferizana92 — APPROVED** [review]
Thanks

**Review by mhmdrezanaderi — APPROVED** [review]
Thank you

**Pull request merged**
