### PR TITLE
Maryam/511 UI signin modal

### PR DESCRIPTION
**Pull request by MaryPG21**
# Description
add modal logIn in landing page and fix conflicts in index.tsx page.

Fixes #511

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

I test it by "submit" and "close" buttons, and both of them work correctly. In addition, check the modal for it open in the right location on the landing page.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ferizana92 — CHANGES_REQUESTED** [review]
Thanks but Please change the type of password in input form.

**Review by ferizana92 — APPROVED** [review]
Thanks.

**Review by mhmdrezanaderi — CHANGES_REQUESTED** [review]
Because we have single page application, you must use `preventDefault` in your `form`
Plz fix in signIn and signUp 
@ferizana92

**Comment by MaryPG21** [comment]
> Because we have single page application, you must use `preventDefault` in your `form` Plz fix in signIn and signUp @ferizana92
fix and debugged this issue.

**Comment by hutan88** [comment]
> > Because we have single page application, you must use `preventDefault` in your `form` Plz fix in signIn and signUp @ferizana92
> 
> fixed bugs from PO : dashboard/signup/sign in should not refresh after submit these page refresh after being clicked add event prevent default

-----------------------------------------------

Thanks...

**Pull request merged**
